### ISSUE TITLE
Demodulizing Policy class name in assert_strong_parameters

### ISSUE THREAD

**Issue by milmih** [ksimmons/policy-assertions#2]
I'm working on a project that requires keeping policy classes in modules and [this](https://github.com/ksimmons/policy-assertions/blob/master/lib/policy_assertions.rb#L62) line is giving me a problem since it is trimming my module names.

Could you give me an explanation why do we need to demodulize Policy class names here? I don't believe that this reflects Pundit functionality for obtaining Policy class names. Be aware of [Manually specifying policy classes](https://github.com/elabs/pundit#manually-specifying-policy-classes).

Thanks!

**Comment by ksimmons** [comment]
@milmih I have pushed a fix to master. If would be helpful if you could test against master before I push an updated gem. Thanks.
